hello: im dev2211AAAA11111111111

app:
  APP_ID: hsit002AAA1111111111
  APP_SECRET: SEPU!PWO@LVE&045#67$AA1111111111
  API_SERVER_URL: http://10.188.182.190:8091/cust-web-api
  isCheck: 0   #接口验证加密开关：0/1
  
management:
  security:
    enabled: false
