server:
  port: 2002
  context-path: /micro-config-client
spring:
  application:
    name: micro-config-client
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
    timeout: 5000

management:
  security:
    enabled: false

hello: prod in
